apiVersion: v1
kind: ReplicationController
metadata:
  name: attribution-database-api
  labels:
    name: attribution-database-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: attribution-database-api
    spec:
      nodeSelector:
        purpose: internal-services
        role: master
      containers:
      - name: attribution-database-api
        image: dr.chefkoch.net/php-crud-api
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secret
          readOnly: true
          mountPath: /app/html/secret
      volumes:
      - name: secret
        secret: {secretName: database}
